# Generated by Django 3.2.9 on 2022-01-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('Adresse', models.CharField(max_length=200, null=True)),
                ('Ville', models.CharField(max_length=100, null=True)),
                ('Pays', models.CharField(max_length=100, null=True)),
                ('Tel1', models.CharField(max_length=50, null=True)),
                ('Tel2', models.CharField(max_length=50, null=True)),
                ('Fax', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('ParDefaut', models.BooleanField(null=True)),
                ('INPE', models.CharField(max_length=50, null=True)),
                ('Photo', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('DateNaissance', models.DateTimeField(null=True)),
                ('Poids', models.FloatField(null=True)),
                ('Taille', models.FloatField(null=True)),
                ('Adresse', models.CharField(max_length=200, null=True)),
                ('Ville', models.CharField(max_length=100, null=True)),
                ('Pays', models.CharField(max_length=100, null=True)),
                ('CodePostal', models.CharField(max_length=100, null=True)),
                ('Tel1', models.CharField(max_length=50, null=True)),
                ('Tel2', models.CharField(max_length=50, null=True)),
                ('Mutuelle', models.CharField(max_length=100, null=True)),
                ('Photo', models.CharField(max_length=200, null=True)),
                ('DateCreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateModification', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialite', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeConsultation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDebut', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateFin', models.DateTimeField(auto_now_add=True, null=True)),
                ('Etat', models.BooleanField(null=True)),
                ('IDMedecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet_medical.medecin')),
                ('IDPatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet_medical.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='IDSpecialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet_medical.specialite'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateConsultation', models.DateTimeField(auto_now_add=True, null=True)),
                ('MontantConsultation', models.FloatField(null=True)),
                ('Gratuit', models.BooleanField()),
                ('DetailConsultation', models.CharField(max_length=100, null=True)),
                ('Regle', models.BooleanField(null=True)),
                ('RestantDu', models.FloatField(null=True)),
                ('DateCreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateModification', models.DateTimeField(auto_now_add=True, null=True)),
                ('IDMedcin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet_medical.medecin')),
                ('IDPatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet_medical.patient')),
                ('IDTypeConsultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet_medical.typeconsultation')),
            ],
        ),
    ]
